{% set name = "OpenPatchMiner" %}
{% set version = "0.1.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/OpenPatchMiner-{{ version }}.tar.gz
  sha256: ee0fa94e00d97d7f82a24102014ff35afb47b7360ac093a0b24d03c5afd44fde

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - keyring
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.6
    - scikit-image
    - tqdm
    - twine
    - wheel
    - zarr
    - tifffile
    - tiffslide

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CBICA/OPM
  summary: A patch miner for large histopathology images
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/CBICA/OPM#usage

extra:
  recipe-maintainers:
    - grenkoca
    - sarthakpati
